### ISSUE TITLE
gnus newsgroup heading displaying the same as screenshot section heading

### ISSUE THREAD

**Issue by boudiccas** [cpaulik/emacs-material-theme#1]
The theme is good except for the "newsgroups" heading in gnus, which is with the same visual display as in your screenshot here of a section heading. This makes the theme unusable in gnus.

**Comment by cpaulik** [comment]
I see. I will try to setup gnus which is something I wanted to do for a long time anyway and then improve the theme.

**Comment by cpaulik** [comment]
This should now be better since I specified the colors now for org-mode specifically. I will have to use gnus more to see which settings I like for it. Any suggestions are welcome

**Comment by boudiccas** [comment]
Christoph Paulik <notifications@github.com> writes:

> This should now be better since I specified the colors now for org-mode specifically. I will have to use gnus more to see which settings I like for it. Any
> suggestions are welcome
>
Thanks, that's much better and looks sane now. :)

Here is my gnus setup, which is at the end of my "init.org" file. It
works fairly well and doesn't need much setup or maintenance.

--8<---------------cut here---------------start------------->8---
** gnus itself
#+BEGIN_SRC emacs-lisp
;;----------------------------------------------------------
;; ---- BEGIN Email client ----
;;----------------------------------------------------------
;; Show errors in this file:
(setq debug-on-error t)

(setq user-full-name "Sharon Kimble"
     user-mail-address "boudiccas@skimble.plus.com")

(setq mail-sources '((file :path "/var/mail/boudiccas")
                                         (pop :server "mail@rhubarb.net" :user "skimble" :password "custard2014")))

(setq gnus-secondary-select-methods '((nnml "")
                                      (nnimap "gmail"     (nnimap-address "imap.gmail.com")))
                                          gnus-select-method '(nnnil ""))

(setq smtpmail-smtp-server "relay.plus.net")
(setq send-mail-function 'smtpmail-send-it)
(setq message-send-mail-function 'smtpmail-send-it)
(require 'smtpmail)
(require 'expiry-hack)

(setq smtpmail-auth-credentials "~/.authinfo")

(setq starttls-use-gnutls t
      starttls-gnutls-program "gnutls-cli")

(add-to-list 'gnus-secondary-select-methods
                         '(nntp "news.gmane.org"
                                        '(nntp "news.gwene.org")
                                        '(nntp "nntp.aioe.org")
                                        '(nntp "news.eternal-september.org")
              (nntp-open-connection-function nntp-open-tls-stream)
              (nntp-port-number 563)))

(setq gnus-visible-headers "^From:\\|^Newsgroup:\\|^Subject:\\|^Date:\\|^Reply-to:\\|^To:")

(setq-default
     gnus-summary-line-format "%U%R%z %(%&user-date;  %-15,15f  %B (%c) %s%)\n"
     gnus-user-date-format-alist '((t . "%Y-%m-%d %H:%M"))
     gnus-summary-thread-gathering-function 'gnus-gather-threads-by-references
     gnus-thread-sort-functions '(gnus-thread-sort-by-most-recent-date)
     gnus-sum-thread-tree-false-root ""
     gnus-sum-thread-tree-indent " "
     gnus-sum-thread-tree-leaf-with-other "├► "
     gnus-sum-thread-tree-root ""
     gnus-sum-thread-tree-single-leaf "╰► "
     gnus-sum-thread-tree-vertical "│"
     gnus-article-browse-delete-temp t
     gnus-fetch-old-headers t
     gnus-treat-strip-trailing-blank-lines 'last
     gnus-keep-backlog 'nil
         gnus-keep-backlog '0)

(setq gnus-thread-sort-functions
      '((not gnus-thread-sort-by-date)))
(setq gnus-article-sort-functions
      '((not gnus-article-sort-by-date)))

(defalias 'yes-or-no-p 'y-or-n-p)

;; auto-sign all mail ;; removed 25/10/14 to see if it still stops me
;; sending emails?
(add-hook 'gnus-message-setup-hook 'mml-secure-message-sign)
(add-hook 'message-setup-hook 'mml-secure-message-sign)

; Use fancy splitting:
(setq nnmail-split-methods 'nnmail-split-fancy
nnmail-split-fancy
 '(| (to "help-bash@gnu\\.org" "help-bash")
     (to "help-gnu-emacs@gnu\\.org" "help-gnu-emacs")
     (to "logcheck@london" "system")
     (any "root@london" "system")
     (any "boudiccas@london" "system")
     ("X-Spam-Flag" "YES" "spam")
     "general"))

(setq message-kill-buffer-on-exit t)

(require 'mm-url)
(defadvice mm-url-insert (after DE-convert-atom-to-rss () )
  "Converts atom to RSS by calling xsltproc."
  (when (re-search-forward "xmlns=\"http://www.w3.org/.*/Atom\""
                           nil t)
    (goto-char (point-min))
    (message "Converting Atom to RSS... ")
    (call-process-region (point-min) (point-max)
                         "xsltproc"
                         t t nil
                         (expand-file-name "~/atom2rss.xsl") "-")
    (goto-char (point-min))
    (message "Converting Atom to RSS... done")))

(ad-activate 'mm-url-insert)

(require 'w3m)
;;You need install the ClI brower 'w3m' and Emacs plugin 'w3m'
(setq mm-text-html-renderer 'w3m)

;; Inline images?
(setq-default mm-attachment-override-types '("image/.*"))

;; prompt for mail replies to newsgroups!!!!!
(defadvice gnus-summary-reply (around reply-in-news activate)
  (interactive)
  (when (or (not (gnus-news-group-p gnus-newsgroup-name))
            (y-or-n-p "REALLY reply with a personal email? "))
    ad-do-it))

;; from Tassilo Horn, 17/7/14
(setq shr-color-visible-distance-min 10
          shr-color-visible-luminance-min 60)
(setq gnus-treat-fill-article 0)

(add-hook 'kill-emacs-hook
          (lambda ()
            (if (gnus-alive-p)
                (gnus-group-exit))))

(add-hook 'message-mode-hook
(lambda ()
  (setq fill-column 68)
  (turn-on-auto-fill)))

 (add-hook 'gnus-article-mode-hook
           (lambda () (setq-local widget-button-face nil)))

(defun cc-fetch-whole-thread()
  "like `A R' `T o' `A T' in the summary buffer."
  (interactive)
  (gnus-summary-refer-references)
  (gnus-summary-top-thread)
  (gnus-summary-refer-thread))

(require 'gnus-namazu)
(gnus-namazu-insinuate)
(setq gnus-namazu-make-index-command "mknmz")
(setq gnus-namazu-make-index-arguments
     '("--all" "--mailnews" "--deny=^.*[^0-9].*$" "--exclude=(SPAM|ham)"))

(defun xsteve-gnus-namazu-update-all-indices ()
  (interactive)
  (gnus-namazu-update-all-indices t))

(defun xsteve-gnus-update-namazu-index ()
(run-at-time "6:00am" nil 'xsteve-gnus-namazu-update-all-indices))

(require 'midnight)
(add-hook 'midnight-hook 'xsteve-gnus-update-namazu-index)
;;http://www.xsteve.at/prg/gnus/
;;[2015-01-07 Wed 13:06]

(setq gnus-message-archive-group "sent.2015")
;;(add-hook 'gnus-started-hook '(lambda ()
;; 		(define-key message-mode-map "\C-ca" 'mailrc-mode)))

#+END_SRC

#+RESULTS:
: sent.2015


#+BEGIN_SRC emacs-lisp
;;# (defun pm/alter-summary-map ()
;;#   (local-set-key "d" [?M ?M ?e ?e down ?g]))

;;# (defun pm/alter-article-map ()
;;#   (local-set-key "d" "MMeen"))

;; to provide an auto-tick without pressing two keys at once
(defun sk/alter-summary-map ()
  (local-set-key "k" [?M ?M ?! ?! down ?g]))
;; FIXME - try removing 'down' in the line above, tangle and then see if it works in gnus, and keeps you still on your tagged line.
(add-hook 'gnus-summary-mode-hook       'sk/alter-summary-map)
;;# (add-hook 'gnus-summary-mode-hook       'pm/alter-summary-map)
;;# (add-hook 'gnus-article-mode-hook       'pm/alter-article-map)
#+END_SRC
[2014-12-11 Thu 03:14]

#+BEGIN_SRC emacs-lisp
;; ;; BBDB: Address list
(require 'bbdb)
(bbdb-initialize 'message 'gnus 'mail)
(setq bbdb-file "~/.emacs.d/bbdb")
(add-hook 'gnus-startup-hook 'bbdb-insinuate-gnus)
(setq bbdb/mail-auto-create-p t
bbdb/news-auto-create-p t)
(defvar bbdb-time-internal-format "%Y-%m-%d"
"The internal date format.")
;;;###autoload
(defun bbdb-timestamp-hook (record)
"For use as a `bbdb-change-hook'; maintains a notes-field called `timestamp'
for the given record which contains the time when it was last modified. If
there is such a field there already, it is changed, otherwise it is added."
(bbdb-record-putprop record 'timestamp (format-time-string
bbdb-time-internal-format
(current-time))))
(add-hook 'message-mode-hook
'(lambda ()
(flyspell-mode t)
(local-set-key "<TAB>" 'bbdb-complete-name)))
#+END_SRC
[2014-12-11 Thu 06:24]

** start up
#+BEGIN_SRC emacs-lisp
;;switch to gnus group buffer or start gnus
(defun my-switch-to-gnus-group-buffer ()
  "Switch to gnus group buffer if it exists, otherwise start gnus"
  (interactive)
  (if (or (not (fboundp 'gnus-alive-p))
          (not (gnus-alive-p)))
      (gnus)
    (switch-to-buffer "*Group*")))
(global-set-key (kbd "C-c n") 'my-switch-to-gnus-group-buffer)
#+END_SRC
[2014-12-21 Sun 13:24]

** misc
#+begin_src emacs-lisp
;;_+ Browse URLs
    (defun gnus-article-browse-urls ()
      "Visit a URL from the `gnus-article-buffer' by prompting via a
    poping up a buffer showing the list of URLs found with the
    `gnus-button-url-regexp'."
      (interactive)
      (gnus-configure-windows 'article)
      (gnus-summary-select-article nil nil 'pseudo)
      (let ((temp-buffer (generate-new-buffer " *Article URLS*"))
            (urls (gnus-article-get-current-urls))
            (this-window (selected-window))
            (browse-window (or (get-buffer-window gnus-article-buffer)
                               ))
            (count 0))
        (save-excursion
          (save-window-excursion
            (set-buffer temp-buffer)
            (mapcar
             (lambda (string)
               (insert (format "\t%d: %s\n" count string))
               (setq count (1+ count))) urls)
            (not-modified)
            (pop-to-buffer temp-buffer)
            (setq count (string-to-number (read-input "Browse which URL: ")))
            (kill-buffer temp-buffer))
          (if browse-window
              (progn (select-window browse-window)
                     (browse-url (nth count urls)))))
        (select-window this-window)))

    (defun gnus-article-get-current-urls ()
      "Return a list of the urls found in the current `gnus-article-buffer'"
      (let (url-list)
        (save-excursion
          (set-buffer gnus-article-buffer)
          (setq url-list (gnus-article-get-urls-region (point-min) (point-max))))
        url-list))

    (defun gnus-article-get-urls-region (min max)
      "Return a list of urls found in the region between MIN and MAX"
      (let (url-list)
        (save-excursion
          (save-restriction
            (narrow-to-region min max)
            (goto-char (point-min))
            (while (re-search-forward gnus-button-url-regexp nil t)
              (let ((match-string (match-string-no-properties 0)))
                (if (and (not (equal (substring match-string 0 4) "file"))
                         (not (member match-string url-list)))
                    (setq url-list (cons match-string url-list)))))))
        url-list))
#+end_src
[2015-01-02 Fri 02:17]

** stats
#+begin_src emacs-lisp
;; Select from summary buffer and run M-x stat RET
(defun stat (beg end)
  (interactive "r")
  (let (header from-list subject-list from subject (n 0) (chars 0))
    (save-excursion
      (goto-char beg)
      (while (< (point) end)
	(setq header (gnus-summary-article-header))
	(incf n)
	(incf chars (mail-header-chars header))
	(setq from (gnus-extract-address-components (mail-header-from header)))
	(setq from (or (car from) (cadr from)))
	(if (assoc from from-list)
	    (incf (cdr (assoc from from-list)))
	  (push (cons from 1) from-list))
	(setq subject (gnus-simplify-subject (mail-header-subject header)))
	(if (assoc subject subject-list)
	    (incf (cdr (assoc subject subject-list)))
	  (push (cons subject 1) subject-list))
	(forward-line)))
    (setq from-list (sort from-list (lambda (a b) (> (cdr a) (cdr b)))))
    (setq subject-list (sort subject-list (lambda (a b) (> (cdr a) (cdr b)))))
    (switch-to-buffer-other-window (get-buffer-create "*stat*"))
    (insert (format "Total number of posts: %i\n" n))
    (insert (format "Average bytes/post: %f\n" (/ (float chars) n)))
    (insert (format "Total number of posters: %i\n" (length from-list)))
    (insert (format "Average posts/poster: %f\n\n" (stat-mean from-list)))
    (stat-top from-list 20)
    (insert (format "\nTotal number of subjects: %i\n" (length subject-list)))
    (insert (format "Average posts/subject: %f\n\n" (stat-mean subject-list)))
    (stat-top subject-list 20)))

(defun stat-mean (alist)
  (let ((mean 0))
    (dolist (x alist)
      (incf mean (cdr x)))
    (/ (float mean) (length alist))))

(defun stat-top (alist &optional n)
  (dotimes (i (if (integerp n)
		  (min n (length alist))
		(length alist)))
    (insert (format "%4i %s\n"
		    (cdr (nth i alist))
		    (car (nth i alist))))))
#+end_src
[2015-01-05 Mon 05:34]
** last seen?
#+begin_src emacs-lisp
(add-hook 'gnus-select-group-hook 'gnus-group-set-timestamp)

(setq gnus-group-line-format
      "%M\%S\%p\%P\%5y: %(%-40,40g%) %ud\n")
(defun gnus-user-format-function-d (headers)
  (let ((time (gnus-group-timestamp gnus-tmp-group)))
    (if time
        (format-time-string "%b %d  %H:%M" time)
      "")))
#+end_src
[2015-01-07 Wed 10:40]

** speed up
#+begin_src emacs-lisp
(setq gc-cons-threshold 3500000)
(setq gnus-use-correct-string-widths nil)
#+end_src
[2015-02-27 Fri 18:45]

** caching
#+begin_src emacs-lisp
(setq gnus-use-cache t)
(setq gnus-cache-directory "~/Mail/cache/")
(setq gnus-cache-enter-articles '(ticked dormant read unread))
(setq gnus-cache-remove-articles nil)
(setq gnus-cacheable-groups "^nnimap")
#+end_src
[2015-02-27 Fri 18:59]

** demon
#+begin_src emacs-lisp
;;(gnus-demon-add-handler 'gnus-group-get-new-news 5 nil)
; Demon to fetch email every 5 minutes when Emacs has been idle for 5 minutes:
(gnus-demon-add-handler 'gnus-demon-scan-news 5 5)
(gnus-demon-init)
#+end_src
[2015-02-27 Fri 19:00]
http://koldfront.dk/text/gnus-email-demon.html

** desktop-notify
#+begin_src emacs-lisp
(require 'gnus-desktop-notify)
(gnus-desktop-notify-mode)
(gnus-demon-add-scanmail)
#+end_src
[2015-02-27 Fri 19:11]

** multi-smtp
#+begin_src emacs-lisp
(defun gnus-set-mail ()
  (interactive)
  (message-goto-from)
  (kill-whole-line)
  (insert "X-Message-SMTP-Method: smtp smtp.googlemail.com 587 example@gmail.com.com\nFrom: Example \n\n")
  (message-goto-body)
  )
#+end_src
[2015-01-20 Tue 07:59]

** new 24.4.1 setup
#+begin_src emacs-lisp
(autoload 'mailrc-mode "mailrc" "Load the file \"mailrc.el(c)\" when the command mailrc-mode is invoked." t)
#+end_src

** testbox
#+begin_src emacs-lisp
(define-key gnus-summary-mode-map "\C-c\C-t" 'gnus-summary-toggle-threads)
#+end_src

#+begin_src emacs-lisp
(defun delete-then-read-next ()
  (interactive)
  (gnus-summary-mark-as-expirable 1)
  (gnus-summary-scroll-up 1)
)
(add-hook 'gnus-summary-mode-hook (lambda ()
    (local-set-key "D" 'delete-then-read-next)
    (local-set-key "d" 'gnus-summary-put-mark-as-expirable-next)
    (local-set-key "u" 'gnus-summary-clear-mark-forward)
    (local-set-key "x" 'gnus-summary-expire-articles)
    (local-set-key "s" 'gnus-summary-move-article)))
#+end_src
[2015-01-21 Wed 05:53]
(defun sk/alter-summary-map ()
  (local-set-key "k" [?M ?M ?! ?! down ?g]))
;; FIXME - try removing 'down' in the line above, tangle and then see if it works in gnus, and keeps you still on your tagged line.
(add-hook 'gnus-summary-mode-hook       'sk/alter-summary-map)
*** alias
#+begin_src emacs-lisp
 '(gnus-alias-override-user-mail-address t)
 '(gnus-alias-unknown-identity-rule (quote error))
 '(gnus-always-read-dribble-file t)
 '(gnus-article-date-lapsed-new-header t)
 '(gnus-article-update-date-headers nil)
 '(gnus-asynchronous t)
 '(gnus-check-new-newsgroups nil)
 '(message-fill-column 78)
 '(message-cited-text ((((class color)) (:foreground "Blue"))))
 '(message-header-cc ((((class color)) (:bold t :foreground "green2"))))
 '(message-header-name ((((class color)) (:bold nil :foreground "Blue"))))
 '(message-header-other ((((class color)) (:foreground "Firebrick"))))
 '(message-header-subject ((((class color)) (:foreground "black"))))
 '(message-header-xheader ((((class color)) (:foreground "Blue"))))
 '(message-mml ((((class color)) (:foreground "DarkGreen"))))
 '(message-separator ((((class color)) (:foreground "Tan"))))
#+end_src
[2015-02-14 Sat 02:26]
From john wigiely git repo

** show images
#+begin_src emacs-lisp
(add-hook
    'gnus-article-prepare-hook
    (lambda ()
            (gnus-article-show-images)))
#+end_src
[2015-03-07 Sat 06:49]
--8<---------------cut here---------------end--------------->8---

Basically I start it with "C-c n" which then runs the .gnus above,
I do "S-l" which brings all the mail-groups, the newsgroups and the
rss-feeds into the display on the screen. I then do "C-c M-g" which
activates everything and runs an rss feed update, and then I can
start reading my emails.

Because everything is in one big org-mode file, I timestamp *every*
block of code that I use as far as possible. Then, when it blows up
in my face I can then search back in the recent code to try to find
the problem. I learnt that after spending four hours looking for an
extra bracket somewhere. If I'd time stamped it it would've only
taken about 20 minutes!

Some useful links -
http://www.xsteve.at/prg/gnus/
http://hack.org/mc/files/.gnus.el
https://github.com/alexott/emacs-configs/blob/master/.gnus
http://mwolson.org/projects/emacs-config/dot_gnus.el.html
http://grapevine.net.au/~striggs/elisp/dot.gnus
http://ivan.kanis.fr/ivan-gnus.el
http://sachachua.com/notebook/emacs/dotgnus.el
http://www.mini-dweeb.org/conf/gnus
https://github.com/alexott/emacs-configs/blob/master/.gnus
http://www.gnus.org/manual/big-gnus.html
http://gnus.org/manual/gnus_407.html#SEC553
http://sachachua.com/blog/category/geek/emacs/
http://www.emacs.uniyar.ac.ru/doc/em24h/emacs172.htm
http://www.emacswiki.org/emacs/GnusTutorial
http://blog.binchen.org/?p=403
http://www.xsteve.at/prg/gnus/
http://koldfront.dk/text/gnus-email-tutorial.html      ; very good beginners tutorial for gnus

Using all that info provided you should be up and going within about
an hour or two! :)

If you want any of my gnus setup explained let me know and I'll be
glad to help. Good luck, and have fun! :)

Sharon.
-- 
A taste of linux = http://www.sharons.org.uk
my git repo = https://bitbucket.org/boudiccas/dots
TGmeds = http://www.tgmeds.org.uk
Debian testing, fluxbox 1.3.7, emacs 24.4.1.0

**Comment by cpaulik** [comment]
Thank you for the detailed guide. I am now able to read RSS feeds and also newsgroups. I've already updated a few colors and will probably tune it more when I use it.
