### ISSUE TITLE
Mode-line on screenshots

### ISSUE THREAD

**Issue by eigengrau** [cpaulik/emacs-material-theme#13]
Great theme! Could you provide some information on you mode-line setup? It seems to go well with the rest of your theme. If that’s a powerline.el theme, you could consider providing that as part of the package.

**Comment by cpaulik** [comment]
Thanks. That is the [Spacemacs](https://github.com/syl20bnr/spacemacs) modeline which is based on powerline AFAIK.

There is already an [issue](https://github.com/syl20bnr/spacemacs/issues/2000) at the spacemacs repo asking for exactly what you want. So you can track the progress there. 

You should also be able to find the necessary setup in the spacemacs source, but I've heard that it is not trivial to extract the modeline.

**Comment by eigengrau** [comment]
Thank you kindly for the pointer!
