### ISSUE TITLE
Faces from cfw

### ISSUE THREAD

**Issue by nlamirault** [cpaulik/emacs-material-theme#16]
Hi,
using cfw [1], some fonts are too dark using the material theme.
Ex: : http://www.hostingpics.net/viewer.php?id=621379201507101049331674x1006scrot.png

[1] : https://github.com/kiwanami/emacs-calfw

**Comment by cpaulik** [comment]
Thanks for reporting this. I'll fix that ASAP.

**Comment by cpaulik** [comment]
Should be fixed now. Please try and see if you like it.

**Comment by nlamirault** [comment]
Yes. Thanks!
