### ISSUE TITLE
AucTeX support?

### ISSUE THREAD

**Issue by justbur** [cpaulik/emacs-material-theme#18]
Hi @cpaulik, 

I was wondering if you could implement support for AucTeX specific faces for the theme. [Here](https://github.com/jordonbiondo/ample-theme/blob/master/ample-theme.el#L691-L707) a list of the relevant faces that I would want defined. It's mostly the section headings that look bad when left to their defaults. 

I don't care too much about the colors. It would just be nice if they came from the theme.

**Comment by cpaulik** [comment]
Thanks for telling me. Should be fixed in the next MELPA build.

**Comment by justbur** [comment]
Great thanks!

**Comment by antoine-levitt** [comment]
Hi,

This commit makes the section titles to be of the same size as the rest of the text. I quite like the section headings being bigger, any chance this can be brought back? To be clear, the ideal behaviour would be the same sizes as the default auctex, but with materials colours.

**Comment by cpaulik** [comment]
Yeah I think it makes sense to structure this similar to the org headlines. I've pushed a first try that looked close to original auctex to me. But nothing bold.

**Comment by antoine-levitt** [comment]
That's much better, thanks! I think the \subsection are more visible than the \section under this scheme, is it supposed to be this way? And I like it better in bold, but that's just taste.

**Comment by cpaulik** [comment]
I'll probably fine tune the ordering of the outline colors so they are from most contrast to least contrast.
