### ISSUE TITLE
Add support for highlight-indentation-mode

### ISSUE THREAD

**Issue by gaudecker** [cpaulik/emacs-material-theme#2]
[More information](https://github.com/antonj/Highlight-Indentation-for-Emacs)

**Comment by cpaulik** [comment]
I hope this looks good to you
![image](https://cloud.githubusercontent.com/assets/380927/6831678/211236a6-d322-11e4-88d2-2fb814fff5c5.png)

**Comment by gaudecker** [comment]
Wow that was fast! Thank you :+1:
