### ISSUE TITLE
Material Prevents Calc Trail Window Appearing

### ISSUE THREAD

**Issue by powellb** [cpaulik/emacs-material-theme#25]
Using clean build of Emacs 24.5.1 in Linux (CENTOS 6.5) as well as Mac OS X, if I install material-theme (via melpa version 20160120.103), the material theme prevents calc-mode from creating the trail window.

Without material-theme, M-x calc will start the calculator mode with two small windows: one is the calculator mode window, the second is the trail window (showing the history). 

However, with material-theme, the second trail window is not shown (calc-mode believes it is displayed; however, its display is not shown).

**Comment by cpaulik** [comment]
Hmm. I can not reproduce that. 

Works fine on my Arch System.

Is the theme really the only thing you are loading or could it be something else?

**Comment by powellb** [comment]
My apologies, I was mistaken. I thought I had left all of my configuration (but disabled all packages) enabled when I tested with and without material-theme. The problem is:

(global-linum-mode t)

If this is enabled, it wrecks the calc trail, regardless of the theme. 

Sorry for the false issue, and I thank you for your material-theme. I enjoy using it. Issue is closed.

**Comment by cpaulik** [comment]
Ok, that explains it. Glad you like the theme.
