### ISSUE TITLE
Support for company-preview-frontend

### ISSUE THREAD

**Issue by fbergroth** [cpaulik/emacs-material-theme#27]
Maybe this frontend is not widely used, but with
```el
(add-to-list 'company-frontends 'company-preview-frontend)
```
the colours are a bit ugly.

With several candidates:
![2016-02-09-100449_194x89_scrot](https://cloud.githubusercontent.com/assets/1211003/12911786/1cc0c8fc-cf15-11e5-91b6-96f2302ae15c.png)
With one candidate:
![2016-02-09-100510_170x57_scrot](https://cloud.githubusercontent.com/assets/1211003/12911798/2a988690-cf15-11e5-9929-cdcee5077cce.png)

If I wasn't completely handicapped when it comes to picking colours, I would have sent you a PR :smile:

**Comment by cpaulik** [comment]
Thanks, I'll look into it.

**Comment by cpaulik** [comment]
Should be fixed now.

**Comment by fbergroth** [comment]
Looks great, thanks!
