### ISSUE TITLE
Modeline : font problem

### ISSUE THREAD

**Issue by nlamirault** [cpaulik/emacs-material-theme#3]
hi,
i just install the theme and load it. I've got strange font into the modeline. My actual theme is monokai. Any idea ?1

![1](https://cloud.githubusercontent.com/assets/29233/7111369/3b2d91b0-e1bf-11e4-8dd3-6b0b356cb478.png)

![2](https://cloud.githubusercontent.com/assets/29233/7111360/1aafd740-e1bf-11e4-97e3-9dbf0b801a41.png)

**Comment by cpaulik** [comment]
Hi,

I tried to reproduce the issue using your [emacs configuration](https://github.com/nlamirault/scame) but could not. I'll try to investigate further but at the moment I have no idea how a theme could cause such a issue.

**Comment by nlamirault** [comment]
Thanks
I try with same configuration on another host, and it works fine. Strange.

**Comment by nlamirault** [comment]
I change font using menu, and it works. Sorry for noise. Thanks for this theme.

**Comment by cpaulik** [comment]
Thanks, no problem. If you encounter any other issues just let me know.
