### ISSUE TITLE
True color support

### ISSUE THREAD

**Issue by anuragm** [cpaulik/emacs-material-theme#33]
Many new terminals and a patched version of Emacs support true color (or 24-bit color) in terminal windows. Can this be enabled in the theme? I have a proposed patch here anuragm@0193c067e2db56b846b813af1a6d77f3da5fd533

**Comment by cpaulik** [comment]
Yes, seems reasonable to me. Cherry picked into master and fixed light colors in https://github.com/cpaulik/emacs-material-theme/commit/048d616e9ba2cb6c77752772423aed52f3699612
