### ISSUE TITLE
Company-mode annotation colours

### ISSUE THREAD

**Issue by jdwaterson** [cpaulik/emacs-material-theme#34]
First of all, thanks for your work on this theme, which I use regularly. It looks great.

One wee problem I'd noticed, however, is that the completion list for company-mode looks broken when annotations are used. I'm not sure how widely annotations are used, but they certainly show up with CIDER when connected to a Clojure REPL, which is where I noticed the problem.

I've now worked out that the problem seems to be that the company-tooltip-annotation-selection face isn't defined, which means that the selected line appears to have a "hole" in the middle of it when annotations are displayed.

I'm now working around it with:

```(set-face-background 'company-tooltip-annotation-selection "#37474f")```

...in my startup file, which works for my setup, but I'm not familiar with theming emacs, so not sure what's needed to make a generic solution.

Just thought you'd want to know.

**Comment by cpaulik** [comment]
Thank you for the tip. Closed in https://github.com/cpaulik/emacs-material-theme/commit/6263ad1ee4c9a6d055986f6c58fa57ad64a71e12

**Comment by jdwaterson** [comment]
Fantastic service! Thanks.
