### ISSUE TITLE
Please create a release for melpa stable

### ISSUE THREAD

**Issue by Trevoke** [cpaulik/emacs-material-theme#37]
All you need to do is tag a commit for "stable" code and push that tag to Github. Every time you do that, melpa will pick it up and create a new package on melpa-stable.

Thanks!

**Comment by cpaulik** [comment]
There is now a tagged version 1.0 so that should get picked up by melpa stable on the next build. You can now also find the melpa stable badge in the readme which should show the status as soon as it is built.

**Comment by Trevoke** [comment]
Awesome, thanks :)
