### ISSUE TITLE
Issue with background in terminal

### ISSUE THREAD

**Issue by krzysztof-magosa** [cpaulik/emacs-material-theme#4]
Hi,

For unknown reason background has weird color while working in terminal.
In graphical emacs version everything is fine.

![screen shot 2015-04-22 at 14 45 45](https://cloud.githubusercontent.com/assets/6112411/7274579/5d4fd208-e8fe-11e4-92c1-3607b79db9ce.png)

**Comment by cpaulik** [comment]
This should look sane now. Unfortunately the [x-term-colors](http://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg) do not support the blue-gray colors like this theme uses a lot. So I had to degrade them to gray values in terminal mode

**Comment by krzysztof-magosa** [comment]
Thank you, now it looks really nice in terminal :)
