### ISSUE TITLE
File type colors in helm-find-files

### ISSUE THREAD

**Issue by humitos** [cpaulik/emacs-material-theme#42]
Hi! Thanks for this awesome theme :)

I want to just ask a question, how do you get the colors by file type in `helm-find-files` in the image you have in the readme? https://raw.githubusercontent.com/cpaulik/emacs-material-theme/master/material-theme.png

I don't get those colors in `helm-find-files` nor `helm-projectile-find-file` :(

Thanks!

**Comment by cpaulik** [comment]
That is strange. I've not configured anything special as far as I remember.

**Comment by humitos** [comment]
Thanks. There should be something in my config that I'm not being able to find then.
