### ISSUE TITLE
No rainbow delimiters

### ISSUE THREAD

**Issue by YichaoCaiDBS** [cpaulik/emacs-material-theme#43]
Hi folks,

I've installed material theme and there seem no rainbow delimiters like it is demonstrated on the github repo.

How do I enable that?

Thank you so much!

**Comment by cpaulik** [comment]
Have you enabled `rainbow-delimiters-mode`? Nothing else should be necessary

**Comment by YichaoCaiDBS** [comment]
Thanks @cpaulik , I do forget to enable the `rainbow-delimiters-mode`. 
Now it works fantastically!!
