### ISSUE TITLE
Theme faces in org-tree-slide

### ISSUE THREAD

**Issue by fbergroth** [cpaulik/emacs-material-theme#46]
The header in org-tree-slide looks a bit off, being black and having lines interspersed.

You can test it with this doc:
```
#+TITLE: Test

* Header 1
** Header 2
*** Header 3
```
and `M-x org-tree-slide-mode`, and navigate slides with `C->` and `C-<`.

**Comment by cpaulik** [comment]
I'm not sure this applies anymore

<img width="260" alt="Screenshot 2021-09-04 at 14 54 47" src="https://user-images.githubusercontent.com/380927/132095109-f8d87786-5ff3-4546-b977-e9327361eb2d.png">

If that does not look right then please re-open
