### ISSUE TITLE
Issue with font in modeline

### ISSUE THREAD

**Issue by euc** [cpaulik/emacs-material-theme#5]
Font in the modeline is not my preferred font, and as far as I know this is the only theme I have this issue with.
[Screenshot](https://cloud.githubusercontent.com/assets/6865240/7290831/1639d046-e9c9-11e4-9ff2-0bf64f7aacc4.png)

**Comment by cpaulik** [comment]
Could you please try with the fix from the commit above? I've copied the basic structure of the theme from the spacegray theme which has set the font-family of the modeline for some reason.

**Comment by euc** [comment]
It works! Thanks so much! :smile:
