### ISSUE TITLE
Add internal-border face.

### ISSUE THREAD

**Issue by zw963** [cpaulik/emacs-material-theme#52]
Please check https://github.com/Alexander-Miller/treemacs/issues/822#issuecomment-899675430

Following is a pop menu, it is no border.

![image](https://user-images.githubusercontent.com/549126/129604546-6bfad32d-718f-42a8-b8e9-8a290aa5ca12.png)

Thank you.

**Comment by cpaulik** [comment]
Looks like this now

<img width="368" alt="Screenshot 2021-09-04 at 14 28 06" src="https://user-images.githubusercontent.com/380927/132094478-b0c3e016-5972-49e7-a08c-448575d6b824.png">
