### ISSUE TITLE
font-lock-string-string-face and font-lock-constant-face have almost the same color

### ISSUE THREAD

**Issue by luxbock** [cpaulik/emacs-material-theme#7]
This means that in `clojure-mode`, strings and keywords (which inherit from `font-lock-constant-face`) look almost the same.

**Comment by cpaulik** [comment]
I hope you like it

![image](https://cloud.githubusercontent.com/assets/380927/7379678/d8b5ea2a-edf6-11e4-8e80-41d7d10aaf70.png)
