### ISSUE TITLE
Consider not overriding foreground color for the region face

### ISSUE THREAD

**Issue by luxbock** [cpaulik/emacs-material-theme#8]
For comparison:

![default](https://dl.dropboxusercontent.com/u/27737622/Screenshots/qVm1.png)

![without](https://dl.dropboxusercontent.com/u/27737622/Screenshots/6GZq.png)

**Comment by cpaulik** [comment]
We were working in parallel here. Fixed in https://github.com/cpaulik/emacs-material-theme/commit/22872e31585f168370b3ca737865553a04f8fc23

**Comment by luxbock** [comment]
Fastest fix ever.
