### ISSUE TITLE
Powerline looks a bit off

### ISSUE THREAD

**Issue by luxbock** [cpaulik/emacs-material-theme#9]
I'm not getting this blue/grayish empty space in other themes I've used:

![screenshot](http://dl.dropboxusercontent.com/u/27737622/Screenshots/JsV8.png)

**Comment by cpaulik** [comment]
That's the `powerline-active2` color. 

I think it looks nice since it separates the left and right messages in the modeline and it makes the difference between active and inactive windows more pronounced

**Comment by luxbock** [comment]
Ah I see. Yeah if it's intentional then by all means leave it be :)
